create table if not exists public.drivers (
  id bigint generated by default as identity primary key,
  name text not null,
  status text default 'available',
  phone text,
  latitude double precision,
  longitude double precision,
  photo_url text,
  created_at timestamptz default now()
);

create table if not exists public.quote_requests (
  id bigint generated by default as identity primary key,
  request_id text unique not null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text,
  pickup_address text not null,
  delivery_address text not null,
  package_type text not null,
  weight_kg numeric not null,
  urgency text not null default 'standard',
  notes text,
  estimated_price numeric not null,
  estimated_eta_hours integer not null,
  status text not null default 'NEW',
  created_at timestamptz default now()
);

create table if not exists public.shipments (
  id bigint generated by default as identity primary key,
  tracking_id text unique not null,
  customer_name text not null,
  customer_email text,
  customer_phone text,
  pickup_address text not null,
  delivery_address text not null,
  package_type text not null,
  weight_kg numeric,
  urgency text default 'standard',
  status text not null default 'BOOKED',
  driver_id bigint references public.drivers(id) on delete set null,
  current_lat double precision,
  current_lng double precision,
  eta text,
  quoted_price numeric,
  package_image_url text,
  proof_image_url text,
  timeline jsonb default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  company text,
  role text not null default 'customer',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists shipments_tracking_id_idx on public.shipments (tracking_id);
create index if not exists shipments_status_idx on public.shipments (status);
create index if not exists shipments_driver_id_idx on public.shipments (driver_id);
create index if not exists quote_requests_status_idx on public.quote_requests (status);
create index if not exists user_profiles_role_idx on public.user_profiles (role);

alter table public.drivers add column if not exists phone text;
alter table public.drivers add column if not exists photo_url text;

alter table public.user_profiles add column if not exists email text;
alter table public.user_profiles add column if not exists full_name text;
alter table public.user_profiles add column if not exists company text;
alter table public.user_profiles add column if not exists role text default 'customer';
alter table public.user_profiles add column if not exists created_at timestamptz default now();
alter table public.user_profiles add column if not exists updated_at timestamptz default now();

alter table public.quote_requests add column if not exists request_id text;
alter table public.quote_requests add column if not exists customer_name text;
alter table public.quote_requests add column if not exists customer_email text;
alter table public.quote_requests add column if not exists customer_phone text;
alter table public.quote_requests add column if not exists pickup_address text;
alter table public.quote_requests add column if not exists delivery_address text;
alter table public.quote_requests add column if not exists package_type text;
alter table public.quote_requests add column if not exists weight_kg numeric;
alter table public.quote_requests add column if not exists urgency text default 'standard';
alter table public.quote_requests add column if not exists notes text;
alter table public.quote_requests add column if not exists estimated_price numeric;
alter table public.quote_requests add column if not exists estimated_eta_hours integer;
alter table public.quote_requests add column if not exists status text default 'NEW';
alter table public.quote_requests add column if not exists created_at timestamptz default now();
create unique index if not exists quote_requests_request_id_idx on public.quote_requests (request_id);

alter table public.shipments add column if not exists tracking_id text;
alter table public.shipments add column if not exists customer_name text;
alter table public.shipments add column if not exists customer_email text;
alter table public.shipments add column if not exists customer_phone text;
alter table public.shipments add column if not exists pickup_address text;
alter table public.shipments add column if not exists delivery_address text;
alter table public.shipments add column if not exists package_type text;
alter table public.shipments add column if not exists weight_kg numeric;
alter table public.shipments add column if not exists urgency text default 'standard';
alter table public.shipments add column if not exists status text default 'BOOKED';
alter table public.shipments add column if not exists driver_id bigint references public.drivers(id) on delete set null;
alter table public.shipments add column if not exists current_lat double precision;
alter table public.shipments add column if not exists current_lng double precision;
alter table public.shipments add column if not exists eta text;
alter table public.shipments add column if not exists quoted_price numeric;
alter table public.shipments add column if not exists package_image_url text;
alter table public.shipments add column if not exists proof_image_url text;
alter table public.shipments add column if not exists timeline jsonb default '[]'::jsonb;
alter table public.shipments add column if not exists created_at timestamptz default now();
alter table public.shipments add column if not exists updated_at timestamptz default now();
