create table if not exists public.drivers (
  id bigint generated by default as identity primary key,
  name text not null,
  status text default 'available',
  phone text,
  latitude double precision,
  longitude double precision,
  photo_url text,
  created_at timestamptz default now()
);

create table if not exists public.quote_requests (
  id bigint generated by default as identity primary key,
  request_id text unique not null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text,
  pickup_address text not null,
  delivery_address text not null,
  package_type text not null,
  weight_kg numeric not null,
  urgency text not null default 'standard',
  notes text,
  estimated_price numeric not null,
  estimated_eta_hours integer not null,
  status text not null default 'NEW',
  created_at timestamptz default now()
);

create table if not exists public.shipments (
  id bigint generated by default as identity primary key,
  tracking_id text unique not null,
  customer_name text not null,
  customer_email text,
  customer_phone text,
  pickup_address text not null,
  delivery_address text not null,
  package_type text not null,
  weight_kg numeric,
  urgency text default 'standard',
  status text not null default 'BOOKED',
  driver_id bigint references public.drivers(id) on delete set null,
  current_lat double precision,
  current_lng double precision,
  eta text,
  quoted_price numeric,
  package_image_url text,
  proof_image_url text,
  timeline jsonb default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists shipments_tracking_id_idx on public.shipments (tracking_id);
create index if not exists shipments_status_idx on public.shipments (status);
create index if not exists shipments_driver_id_idx on public.shipments (driver_id);
create index if not exists quote_requests_status_idx on public.quote_requests (status);

alter table public.drivers add column if not exists phone text;
alter table public.drivers add column if not exists photo_url text;
